### ISSUE TITLE
V1.2.0 Release

### ISSUE THREAD

**Issue by anthonysena** [anthonysena/cmtest#2]
### Release Version V1.2.0
- [ ] Run Unit Tests
- [x] Generate Release Notes
- [x] Complete user acceptance testing
- [x] Obtain sign off
- [x] Tag as V1.2.0
- [x] Communicate production change to team
- [ ] Update OHDSI.org
- [ ] Communicate release via OHDSI forums
- [x] Celebratory adult beverage of choice
